export const IPC = {
  CHARACTER_CLICKED: 'character:clicked',
  CHARACTER_RIGHT_CLICKED: 'character:right-clicked',
  OVERLAY_READY: 'overlay:ready',
  UPDATE_CHARACTERS: 'characters:update',
  SET_THINKING: 'character:thinking',
  SET_THINKING_DONE: 'character:thinking-done',
  SHOW_COMPLETION_BUBBLE: 'character:completion-bubble',
  SEND_MESSAGE: 'session:send-message',
  POPOVER_READY: 'popover:ready',
  SLASH_COMMAND: 'session:slash-command',
  CHANGE_PROVIDER: 'session:change-provider',
  REFRESH_SESSION: 'session:refresh',
  COPY_LAST: 'session:copy-last',
  STREAM_TEXT: 'session:stream-text',
  TOOL_USE: 'session:tool-use',
  TOOL_RESULT: 'session:tool-result',
  TURN_COMPLETE: 'session:turn-complete',
  SESSION_ERROR: 'session:error',
  SESSION_CLEAR: 'session:clear',
  THEME_CHANGED: 'theme:changed',
  SETTINGS_CHANGED: 'settings:changed',
  MOUSE_POSITION: 'mouse:position',
  SET_CLICK_THROUGH: 'overlay:set-click-through',
  PLAY_SOUND: 'sound:play',
} as const;
